<a href="https://colab.research.google.com/github/kkh9372/Colab/blob/main/Ch1.%ED%8C%8C%EC%9D%B4%EC%8D%AC%20%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%B6%84%EC%84%9D%20%EA%B8%B0%EC%B4%88/2_Numpy_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/10/18
이름 : 김관후
내용 : 파이썬 Numpy 패키지 실습하기

Numpy 라이브러리
  - 고성능의 수치계산을 위한 파이선 라이브러리
  - 파이썬의 기본 리스트보다 월등한 연산 성능
  - 행렬이나 대규모 다차원 배열 처리를 지원
  """
import numpy as np

In [ ]:
# numpy 벡터
v1 = np.array([1, 2, 3, 4, 5])
print('v1 :', v1)

v2 = np.arange(5)
print('v2 :', v2)

v3  = np.arange(10)
print('v3 :', v3)



In [ ]:
# 0 ~ 1 사이의 임의의 실수 100개
result1 = np.random.rand(100)

# 표준정규분포를 따르는 실수 100개
result2 = np.random.rand(100)

# 0 ~ 9 사이의 임의의 정수
result3 = np.random.randint(10)


In [ ]:
result1, result2, result3

In [ ]:
#numpy 행렬
m1 = np.array([[1, 2], [3, 4]])
print(m1)

m2= np.array([[1,2, 3], [4, 5, 6], [7, 8, 9]])
print(m2)

m3 = np.ones([2, 4])
print(m3)

m4 = np.zeros([3, 2])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# 행렬 인덱싱
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(mat)

print(mat[0, 0])
print(mat[0, :])
print(mat[:, 0])

print(mat[0:2, 0:2])
print(mat[:, 0:2])
print(mat[:, 2:4])
print(mat[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
